services:
  front:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    tty: true
    ports:
      - 3000:3000
    stdin_open: true
    # プロジェクトディレクトリにマウントする
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm i && npm run dev"
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./work:/work
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--LabApp.token=''"]
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: